# Generated by Django 3.2.2 on 2021-05-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
