# Generated by Django 3.2 on 2021-06-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryApp', '0002_diary_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
